[package]
name = "ebpf"
version = "0.1.0"
publish = false
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }

[dependencies]
aya-ebpf = "0.1.1"
aya-log-ebpf = "0.1.0"
zerocopy = { version = "0.7", features = ["derive"] }

[features]
default = []
trace = []

[[bin]]
name = "raknet-xdp-ebpf"
path = "src/main.rs"

[lints]
workspace = true
